version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"

  database:
    build:
      context: ./database
    ports:
      - "1433:1433"
