version: '3'

services:
  app-server:
    build:
      context: ./app-server
    ports:
      - "3000:3000"
      
  web-server:
    build:
      context: ./web-server
    ports:
      - "5000:5000"

  db-server:
    build:
      context: ./db-server
    ports:
      - "1433:1433"
