apiVersion: v1
kind: Service
metadata:
  name: app-server-loadbalancer
spec:
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: app-server-nodeport
spec:
  selector:
    app: app-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort