apiVersion: v1
kind: Service
metadata:
  name: db-server-loadbalancer
spec:
  selector:
    app: db-server
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: db-server-nodeport
spec:
  selector:
    app: db-server
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort