apiVersion: v1
kind: Service
metadata:
  name: web-server-loadbalancer
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-nodeport
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort