apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-server
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
      - name: db-server
        image: sailesh081/demo-app-devops-db-server:latest
        ports:
        - containerPort: 3306
