name: Deploy sample application using CI/CD to Kubernetes with Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker images
        run: docker-compose build

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./kube_deploy/deployments/app-server-deployment.yml --validate=false
          kubectl apply -f ./kube_deploy/deployments/db-server-deployment.yaml --validate=false
          kubectl apply -f ./kube_deploy/deployments/web-server-deployment.yaml --validate=false
          kubectl apply -f ./kube_deploy/services/app-server-services.yml --validate=false
          kubectl apply -f ./kube_deploy/services/db-server-services.yml --validate=false
          kubectl apply -f ./kube_deploy/services/web-server-services.yml --validate=false

